### PR TITLE
Fix create_check_run error by updating octokit in Gemfile

### PR DESCRIPTION
**Pull request by andrew-ongh**
The default "bundle install" downloads Octokit 4.13.0, which is not compatible with the Checks API tutorial because the Checks API tutorial uses create_check_run() which is not in Octokit 4.13.0 

Checks API tutorial: https://docs.github.com/en/developers/apps/guides/creating-ci-tests-with-the-checks-api#part-2-creating-the-octo-rubocop-ci-test

```
bundle install
Fetching gem metadata from http://rubygems.org/.......
Following files may not be writable, so sudo is needed:
  /Library/Ruby/Gems/2.6.0
  /Library/Ruby/Gems/2.6.0/build_info
  /Library/Ruby/Gems/2.6.0/cache
  /Library/Ruby/Gems/2.6.0/doc
  /Library/Ruby/Gems/2.6.0/extensions
  /Library/Ruby/Gems/2.6.0/gems
  /Library/Ruby/Gems/2.6.0/specifications
Fetching public_suffix 3.0.3


Your user account isn't allowed to install to the system RubyGems.
  You can cancel this installation and run:

      bundle install --path vendor/bundle

  to install the gems into ./vendor/bundle/, or you can enter your password
  and install the bundled gems to RubyGems using sudo.

  Password: 
Sorry, try again.


Your user account isn't allowed to install to the system RubyGems.
  You can cancel this installation and run:

      bundle install --path vendor/bundle

  to install the gems into ./vendor/bundle/, or you can enter your password
  and install the bundled gems to RubyGems using sudo.

  Password: 
Installing public_suffix 3.0.3
Fetching addressable 2.5.2
Installing addressable 2.5.2
Using bundler 1.17.2
Fetching dotenv 2.5.0
Installing dotenv 2.5.0
Fetching multipart-post 2.0.0
Installing multipart-post 2.0.0
Fetching faraday 0.15.3
Installing faraday 0.15.3
Fetching jwt 2.1.0
Installing jwt 2.1.0
Fetching mustermann 1.0.3
Installing mustermann 1.0.3
Fetching sawyer 0.8.1
Installing sawyer 0.8.1
Fetching octokit 4.13.0
Installing octokit 4.13.0
Fetching rack 2.2.2
Installing rack 2.2.2
Fetching rack-protection 2.0.4
Installing rack-protection 2.0.4
Fetching tilt 2.0.8
Installing tilt 2.0.8
Fetching sinatra 2.0.4
Installing sinatra 2.0.4
Bundle complete! 4 Gemfile dependencies, 14 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

### CODE REVIEW

**Comment by bulletwhisper77** [comment]
k

**Comment by robandpdx** [comment]
This PR includes a lot more changes than an update to the Gemfile. Please isolate the intended change from all the unintended changes. I think PR from master in your fork is a mistake! If I were you, I'd create a new branch from some commit before all your changes. Then I would cherry-pick the one change you want to merge here, and open a new PR from the branch.

**Comment by bulletwhisper77** [comment]
hey ty for responding, and i apologize for my mistakes i shouldve never
messed with it im not a developer of coarse you know that already lol but
reason i messing with github i was hacked by someone  from facebook lured
me in with crypto saying that i had alot money invested in crypto and other
stock he used my credentials with his email and lock me out so i
couldnt see what he was doing i am now interested in learning developing
and crypto but i recently got new phone sold old one 2 factor got me locked
out cant get in cause dont have old phone

**Comment by bulletwhisper77** [comment]
im not trying to do anything illegal so if u and github  team can help  im
very grateful but it does say i have alot on google finance portfolio

**Pull request closed without merging**
